### PR TITLE
Feature/issue 395 Indicate object in cold storage

### PR DESCRIPTION
**Pull request by suryasaha**
Indicate that a given access method is to cold/offline/less available storage

A DRS object is said to be in 'Cold' storage when it is not immediately available via a DRS request. Hot/Cold is binary. Goal is to indicate that a given access method is to a cold/offline/less available storage. Please see https://github.com/ga4gh/data-repository-service-schemas/issues/395 for community discussion.

We are taking a phased approach. For Phase 1, we just want to answer this question:
Can the user can retrieve the file at the moment of the request?
 - If the user can do that, than the file is in "hot" storage, and can be used right away.
 - If the user cannot retrieve the file, then the file is simply in not available. It is in some form of cold/offline/less available storage.

In phase 2, we can think about having a better way to provide details on the storage and the thawing process.

### CODE REVIEW

**Comment by briandoconnor** [comment]
See cloud work stream discussion notes from last DRS discussion from 2/12/24: https://docs.google.com/document/d/1hayvWLIoymomPI9oXcaTZirn5YxFv1cYAs70zyvlvnA/edit#bookmark=id.stgpsb1mhzwn

**Comment by mattions** [comment]
quick note form Connect Switzerland, recording the decision:

Let's make it an enumeration: --> immediate, delayed as the two terms.
Lots of thumbs up in the room.

**Comment by suryasaha** [comment]
Interest from driver projects at Connect: CRDC, BDC, SRA, European 1M genomes project, AnVIL, Australian Genomics

**Comment by suryasaha** [comment]
@ianfore I am using _availability_ as the label now with boolean value. Do you think this looks better?

**Comment by briandoconnor** [comment]
as of 20240812 we decided the boolean is the right way to go.  We can discuss delay time reporting back during the thaw mechanism

**Pull request merged**
