### PR TITLE
Reduced down the list of access methods

### PR DESCRIPTION
**Pull request by briandoconnor**
See #240, it would be extremely helpful to use that issue to collect what access methods are needed by each driver/implementation.  And we can propagate any changes to the list of access methods via this feature branch before merging.

See also issue #241 for the list of known DRS implementations.

### CODE REVIEW

**Comment by briandoconnor** [comment]
See https://ga4gh.github.io/data-repository-service-schemas/preview/feature/issue-240-list-access-methods/swagger-ui/#/

**Comment by briandoconnor** [comment]
OK, I got feedback from quite a few drivers/implementers.  @dglazer can you take a look?

**Comment by dglazer** [comment]
@shaikh-rashid -- can you say a bit more about CanDIG's requirements? How do you plan to retrieve data objects if you're not using an `access_method` ?

**Comment by junjun-zhang** [comment]
+1 from ICGC-ARGO

**Comment by jorizci** [comment]
+1 From EGA

**Comment by susheel** [comment]
+1 ELIXIR

**Comment by briandoconnor** [comment]
@sarpera brings up htsget vs https, needed for htsget?

@delagoya brings up that there are additional methods supported by htsget that clients need to know about.

@jorizci will take a look to make sure this understanding is correct

**Comment by susheel** [comment]
htsget - https://samtools.github.io/hts-specs/htsget.html

**Pull request merged**
