### PR TITLE
correct PostObject 200 response

### PR DESCRIPTION
**Pull request by dvoet**
fix for https://github.com/ga4gh/data-repository-service-schemas/issues/375

### CODE REVIEW

**Comment by briandoconnor** [comment]
Yep, not sure how this typo got in there but @dvoet is totally right here.  

Doug, in your PR you want to merge to "master".  Can you change to "develop" instead?  I'm happy to then to the release process to get out a 1.2.1 that includes this fix.

Thanks!!!

**Review by briandoconnor — CHANGES_REQUESTED** [review]
Approves but raise the PR to develop and then @jb-adams or I will take it from there for a release

**Comment by dvoet** [comment]
> Approves but raise the PR to develop and then @jb-adams or I will take it from there for a release

done

**Comment by dvoet** [comment]
any update on merging this

**Review by jb-adams — APPROVED** [review]

**Comment by jb-adams** [comment]
@briandoconnor do you want to make the merge? Following this I can make a re-release of 1.2.0 as we discussed

**Comment by dvoet** [comment]
ping

**Comment by dvoet** [comment]
@briandoconnor @jb-adams  ping - this is a real problem for anyone using codegen based on this api definition. Can we get this simple correction merged?

**Comment by jb-adams** [comment]
@briandoconnor @dglazer can you make the final call on if this is good to merge? Following the merge, I can re-release DRS 1.2.0

**Comment by dglazer** [comment]
I haven't been tracking, but this looks like a straightforward fix to a typo -- fine with me to move forward, as long as @briandoconnor 's process comments about order-of-merging are followed.

**Pull request merged**
