### PR TITLE
Data Bundle Access URL (2/2)

### PR DESCRIPTION
**Pull request by susheel**
This is to provide a mirror of the GetAccessURL method for Data Bundles. Users may request access to a folder/bundle/collection of objects as a whole.

### CODE REVIEW

**Comment by dglazer** [comment]
FYI, I'm quiet here because I've included higher-level questions about this PR in the discussion on #244.

My thoughts partly depend on what it means to "fetch the actual bundle bytes" -- what bytes are returned?

**Comment by dglazer** [comment]
@susheel -- I think that #258 (object/bundle unification) makes this PR no longer relevant -- do you agree?

**Comment by susheel** [comment]
@dglazer I agree. I would close it after #258 is merged.

**Comment by briandoconnor** [comment]
So @susheel and @dglazer I'm assuming you both want to hold off on review for this until we find out what happens with #258

**Comment by dglazer** [comment]
Correct. -- I'm optimistic we won't need to review this one.

*From: *briandoconnor <notifications@github.com>
*Date: *Mon, May 13, 2019 at 7:11 AM
*To: *ga4gh/data-repository-service-schemas
*Cc: *David Glazer, Mention

So @susheel <https://github.com/susheel> and @dglazer

**Comment by dglazer** [comment]
@susheel , closing since #258 is now merged.

**Pull request closed without merging**
