### PR TITLE
Release/drs 1.4.0

### PR DESCRIPTION
**Pull request by briandoconnor**
## About

This is a PR for drivers/implementers to vote on the DRS 1.4 release.

See the human readable documentation for DRS 1.4 [here](https://ga4gh.github.io/data-repository-service-schemas/preview/feature/issue-334-drs-bulk-requests/docs/#tag/Objects/operation/GetBulkObjects/).

We would like to have voting done by **Oct 22nd 2023** so we can merge and release DRS 1.4 (using HubFlow) in the cloud meeting on the 23rd.

## Voting Process

Driver projects/implementers, please add a comments that includes the following information:
- **Name**: Driver Project or DRS Implementer Name
- **Vote**: -1 if you don't agree with release 1.4 in its current form, 0 if you're neutral, and +1 if you are comfortable with this release
- **Comments**: any comments you have, in particular if you voted "-1"

## Release

When voting has completed and any concerns resolved, we will use HubFlow to perform a release (merge to develop and master, tag a release on GitHub).

### CODE REVIEW

**Comment by ohofmann** [comment]
Name: Australian Genomics
Vote: 0
Comments: We are not using DRS at this time and have not explored the standard in sufficient detail to comment

**Comment by MichaelLukowski** [comment]
Name: CRDC (Driver Project + Implementer), Biomedical Research Hub (Driver Project + Implementer)
Vote: +1

**Comment by mbarkley** [comment]
Name: Autism Sharing Initiative (Driver Project)
Vote: 0
Comments: We don't currently have concrete plans to use the bulk operations added in this release, so we don't have a strong opinion on the content of this release.

**Comment by briandoconnor** [comment]
I updated the release branch so it can merge cleanly into master

Given the votes, I will move forward the release via HubFlow

**Pull request merged**
