### PR TITLE
Rename and clarify Object timestamp fields

### PR DESCRIPTION
**Pull request by dglazer**
Addresses [DRS v1 PRC #6 - Object Time Fields](https://docs.google.com/document/d/1gCTFFomdUhP7dPJD6H-eqQ77OmLszvKGDqJXaBkU9SU/edit#heading=h.iybpte35csxw)

### CODE REVIEW

**Comment by susheel** [comment]
+1 ELIXIR

**Comment by Avantol13** [comment]
+1 from DCF/UChicago/CTDS/Gen3/<insert other identifiers here>

**Comment by pr80ik** [comment]
+1

**Comment by mattions** [comment]
+0 from Seven Bridges (CGC, Cavatica)

**Comment by dglazer** [comment]
Looks like this is already merged -- lmk if there's more to do.

**Pull request merged**
