### PR TITLE
Feature/issue 348 post passport

### PR DESCRIPTION
**Pull request by briandoconnor**
See Issue #348

### CODE REVIEW

**Comment by dglazer** [comment]
OpenAPI question -- do we need to duplicate the content of the POST and GET endpoints? It would be a lot easier to read (and to maintain) if we could share the duplicated part.

**Comment by briandoconnor** [comment]
Bigger issue @dglazer is this is swagger 2.0... not OpenAPI which is what we should move towards as a project.  I'd prefer to not invest a lot of time figuring out how to do this in the old swagger language and focus on cleaning it up in the move to OpenAPI 3

**Comment by dglazer** [comment]
I agree we should move to OpenAPI 3 asap -- @jb-adams to make sure that's on the list.
I'm not sure that will help with this particular issue, but I agree it's not worth debugging in swagger syntax.

**Comment by jb-adams** [comment]
Looks like #230 aims to migrate to OpenAPI 3. @jaeddy @uniqueg has there been any movement on this lately? I can take this branch if you have no bandwidth currently

**Comment by briandoconnor** [comment]
@jb-adams , it would be fantastic to move the OpenAPI 3 work forward and coordinate that with @jaeddy as part of the trans GA4GH effort to have common doc build approaches across our repos.

**Comment by uniqueg** [comment]
Thanks @jb-adams that would be appreciated. Very little bandwidth here in May and June, unfortunately.

**Comment by briandoconnor** [comment]
I'm closing this PR in favor of #363 which uses OpenAPI 3

**Pull request closed without merging**
