### PR TITLE
Feature/issue 343 metadata endpoint

### PR DESCRIPTION
**Pull request by MichaelLukowski**
This is a PR for introducing a new metadata endpoint that supports an arbitrary JSON response at a new `/metadata/{object_id}` endpoint.

There is a need for requestor pays and egress for additional metadata of DRS objects that shouldn't be included in the `/object` endpoint.

This will also be useful for a best practice of "complex objects" where one DRS id can point to a json file that describes many DRS objects.

### CODE REVIEW

**Comment by dglazer** [comment]
Sorry if I missed earlier discussion of this PR, but I'm not following the intended use of this new method, or how it would address the stated goals fetching requestor-pays content or supporting complex objects. Is there more background somewhere? (I did look at #343 and didn't see answers there.) I'll reserve most comments until I hear back, but in general I think providing a method that returns arbitrary unspecified metadata creates a big risk of breaking interoperability.

**Comment by ianfore** [comment]
Referring back to this [hackathon exploration](https://github.com/ga4gh/fasp-scripts/blob/master/notebooks/drs/altMetadata.ipynb) and [the DRS issue](https://github.com/ga4gh/data-repository-service-schemas/issues/336) that generated it.

It may be a separate use case - all depends on exactly what metadata are intended in each situation. The hackathon was following an approach that aligns with "bundling alternatives" described in PR 389. Both 336 and 389 rely on higher level schemas that provide the metadata.

Despite the ambiguity, the motivation of this issue and 389 seems to be the same. So am also waiting on what @dglazer asked.

Commenting on 
`arbitrary unspecified metadata creates a big risk of breaking interoperability.`
Yes, a shared concern. A key characteristic of the protocols (e.g. Data Connect)  that provide the higher level schemas is that allow for, and encourage, for those metadata to be well specified.

**Comment by briandoconnor** [comment]
@MichaelLukowski just wanted to check in with you on this PR

To keep this on track for Connect in April 2023 can you confirm the following:

Champion → @MichaelLukowski 
Deadline for revisions: ?
Deadline for comments: ?
Merge date: ? (3/13 at latest)

**Comment by briandoconnor** [comment]
@MichaelLukowski suggested this might be closed and replaced with GA4GH Connect... since it already provides the ability to specify a metadata definition.

**Comment by briandoconnor** [comment]
https://github.com/ga4gh-discovery/data-connect

**Comment by briandoconnor** [comment]
@ianfore has an example that we can point to... from FASP work.  Ian can you drop links here?

**Review by briandoconnor — CHANGES_REQUESTED** [review]
Based on Cloud call on 1/23/23 it sounds like Michale wants to withdraw this PR and recommend using Data Connect.

@MichaelLukowski can you document this decision here and point to data connect, maybe an example of how to do a call to data connect to get back DRS URIs + metadata

**Comment by briandoconnor** [comment]
Examples from @ianfore 
Examples:
DRS and metadata exploration
https://github.com/ga4gh/fasp-scripts/blob/master/notebooks/drs/altMetadata.ipynb
https://github.com/ga4gh/fasp-scripts/tree/master/notebooks/drs

**Pull request closed without merging**
