### PR TITLE
Doc updates DRS v1 SecReview comments

### PR DESCRIPTION
**Pull request by susheel**
Doc updates to address [DRS v1 SecReview](https://docs.google.com/document/d/1MaV8GX0xLLq3jZ8BGHGLEkY5rlHwWopyHOWEkV5NeiE/edit#) comments

### CODE REVIEW

**Comment by susheel** [comment]
+1 ELIXIR

**Comment by ddietterich** [comment]
+1 Terra

**Comment by dglazer** [comment]
This PR doesn't add or remove any references to /service-info, so I think that's a separate issue that can be dealt with (if needed) in a separate PR. Agree this one is correctly merged and closed.

**Comment by susheel** [comment]
This PR incorrectly targets the `master` branch rather than the intended `release/drs-1.0.0` branch. My bad. I think we can leave this as-is for master.

@briandoconnor Please merge PR #290 to correct this merge to `release/drs-1.0.0`

**Comment by susheel** [comment]
@briandoconnor @dglazer Added #291 to track the `/service-info` cleanup

**Comment by sevsnap** [comment]
Please add a reference to the AAI specification as suggested in [DRS v1 SecReview](https://docs.google.com/document/d/1MaV8GX0xLLq3jZ8BGHGLEkY5rlHwWopyHOWEkV5NeiE/edit#). You can do this by referencing the [correspondent repository](https://github.com/ga4gh/data-security/blob/master/AAI/AAIConnectProfile.md)

**Comment by susheel** [comment]
@sevsnap We've created #295 which we will merge as soon as the GA4GH AAI standard is confirmed. Could you notify us after your approval process?

**Pull request merged**
