### PR TITLE
Removed artifacts from protobuf translation within response object schema

### PR DESCRIPTION
**Pull request by delagoya**
* ErrorResponse -> Error
  * ServiceInfoResponse -> ServiceInfo
  * /bundles/{bundle_id}#get reference GetBundleResponse -> Bundle
  * /objects/{object_id}#get reference GetObjectResponse -> Object
  * Removed GetBundleResponse and GetObjectResponse envelope objects
  * GetAccessURLResponse -> AccessURL

Addresses Issue #242

### CODE REVIEW

**Comment by dglazer** [comment]
@delagoya , this is looking good to me. (And doing a quick check of the WES schema, it's already halfway between the old and new models -- it still has `ErrorResponse` and `RunListResponse`, but all the other methods just return what they need to return.)

Do you have more changes in mind, or do you think this covers it?
And do you have any concerns about the way it landed, or are you liking it?

**Comment by delagoya** [comment]
It would be good if the Error object could be standardized across the API's, but open to suggestions on how to implement this. May be worth it's own issue & PR

Looks like @susheel addressed the `etag` vs  `multipart-md5` issue and some dangling unused schema objects in PR #246 

Any other schema changes are unrelated to this issue, so I would propose those go in another issue + PR.

**Comment by dglazer** [comment]
Got it. Looking a bit more closely:
- Get{Bundle,Object,AccessURL}Response are the meat of this PR, and I agree they simplify things, so LGTM.
- ErrorResponse and ServiceInfoResponse are just renames; they don't change the API structure at all, and the new names are a little cleaner, so LGTM also. I agree we should standardize across our APIs, but don't feel the need to do that for 0.1

@delagoya -- sounds like we should push this forward -- please add @briandoconnor and me as official reviewers if you agree, so we can LGTM officially and add it to the list we want the driver projects to review.

**Comment by delagoya** [comment]
@dglazer  I do not have permission to assign reviewers (or anything else other than submit the issue and PR). @rishidev?

**Comment by briandoconnor** [comment]
LGTM, and I agree to push future changes to the PR from Susheel and also future PRs.  I'm giving my thumbs up on this PR in the mean time

**Comment by ohofmann** [comment]
+1 from AGHA.

**Comment by junjun-zhang** [comment]
+1 from ICGC-ARGO

**Comment by susheel** [comment]
+1 ELIXIR

**Pull request merged**
